# Todor's image
FROM ta/gym
RUN pip install keras-rl
RUN mkdir /delay
WORKDIR /root
#VOLUME . /delay
#RUN git clone -b ddpg_pendulum https://github.com/ipab-rad/delay_rl.git
#WORKDIR /delay
#RUN pip install -e gym-delayedpendulum
